### ISSUE TITLE
Coloc with GTEx data: WARNING - R[write to console]: Error in process.dataset(d = dataset1, suffix = "   dataset df1: Length of snp names and beta vectors must match

### ISSUE THREAD

**Issue by lauraand1705** [hakyimlab/summary-gwas-imputation#11]
Hi,
I am running the below script, but gets this error: 

WARNING - R[write to console]: Error in process.dataset(d = dataset1, suffix = "dataset df1: Length of snp names and beta vectors must match

python3 ../summary-gwas-imputation/src/run_coloc.py \
-gwas_mode bse \
-gwas ../metaXcan/meta_harm_200803.tab.gz \
-eqtl_mode bse \
-eqtl ../data/GTEx_Analysis_v8_eQTL/Heart_Atrial_Appendage.v8.egenes.txt.gz \
-gwas_sample_size 32036 \
-eqtl_sample_size 372 \
-parsimony 8 \
-output test > /dev/null

Can you help me with this error message?
Best regards,
Laura.

**Comment by Heroico** [comment]
Hi Laura,

Unfortunately this script is undocumented and provided as-is.
You would have to debug it with your data. You can use the argument `--keep_intermediate_folder`, so that you can inspect the internal artifacts fed to coloc's R script `src\ncoloc.R` by this script.

Best,

Alvaro
