### ISSUE TITLE
post-processing of imputed chromosome files

### ISSUE THREAD

**Issue by romlindien** [hakyimlab/summary-gwas-imputation#14]
Hi,

I work on Mac OS Mojave, under the 'IMLABTOOLS' conda environment with the original .yaml file (and I get the same issues with python 3.6 and numpy 1.15.4), and everything went fine so far, including performing prediXcan after quick harmonization using beta03.py. I wanted to use imputation. However, two issues prevent me from merging the 22 chromosome files generated using harmonization with gwas_parsing.py and imputed using gwas_summary_imputation.py. 

Here is the head view of my harmonized gwas:

variant_id	panel_variant_id	chromosome	position	effect_allele	non_effect_allele	frequency	pvalue	zscore	effect_size	standard_error	sample_size	n_cases
rs11804171	NA	chr1	788439	A	T	0.057	0.09182	-1.6858743	-0.0256	0.0152	121604	121604
rs2977670	NA	chr1	788511	C	G	0.9428	0.0812	1.7437655	0.0268	0.0154	121604	121604
rs12138618	NA	chr1	814855	A	G	0.0657	0.10800000000000001	-1.607248	-0.0347	0.0216	121604	121604
rs3094315	NA	chr1	817186	A	G	0.7837	0.774	0.2871467	0.0013	0.0046	121604	121604

Here is the head view of my imputed summary stats (chr1):

variant_id	panel_variant_id	chromosome	position	effect_allele	non_effect_allele	frequency	zscore	variance	imputation_status	n	n_indep	most_extreme_z
rs141149254	chr1_54490_G_A_b38	chr1	54490	A	G	0.17766990291262136	-0.9087151299792123	0.15151489339740898	imputed	177	177	-2.7700946
rs188486692	chr1_87021_T_C_b38	chr1	87021	C	T	0.011650485436893204	-0.2811373416113958	0.14101801962612653	imputed	177	177	-2.7700946
rs112455420	chr1_263722_C_G_b38	chr1	263722	G	C	0.12233009708737864	0.13789682101193423	0.18880870467012337	imputed	177	177	-2.7700946
rs144425991	chr1_594402_C_T_b38	chr1	594402	T	C	0.02621359223300971	-0.1837089639958824	0.11961914002691187	imputed	177	177	-2.7700946

Using the following code for post-processing: 

python ../summary-gwas-imputation-master/src/gwas_summary_imputation_postprocess.py \
-gwas_file /Users/roicick/Desktop/HOT_STUFF/VGLUT_paper/draft_jan21/VGLUT_TWAS/AUD_harmo_final.txt.gz \
-folder imputed/AUD_UKBB/ \
-pattern AUD_UKBB_imputed_chr* \
-parsimony 7 \
--keep_criteria CHR_POS \ *******i used both options and also the code without this parameter*******
-output imputed/AUD_UKBB_imputed.txt.gz

I get two issues:

1) a known numpy issue, as follows: /Users/roicick/miniconda3/envs/imlabtools/lib/python3.6/site-packages/numpy/lib/arraysetops.py:522: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

*****which does not occur when using the '--keep_criteria CHR_POS' parameter*******

2) INFO - Beginning process
INFO - Processing imputed AUD_UKBB_imputed_chr1
INFO - Processing imputed AUD_UKBB_imputed_chr10
INFO - Processing imputed AUD_UKBB_imputed_chr11
INFO - Processing imputed AUD_UKBB_imputed_chr12
INFO - Processing imputed AUD_UKBB_imputed_chr13
INFO - Processing imputed AUD_UKBB_imputed_chr14
INFO - Processing imputed AUD_UKBB_imputed_chr15
INFO - Processing imputed AUD_UKBB_imputed_chr16
INFO - Processing imputed AUD_UKBB_imputed_chr17
INFO - Processing imputed AUD_UKBB_imputed_chr18
INFO - Processing imputed AUD_UKBB_imputed_chr19
INFO - Processing imputed AUD_UKBB_imputed_chr2
INFO - Processing imputed AUD_UKBB_imputed_chr20
INFO - Processing imputed AUD_UKBB_imputed_chr21
INFO - Processing imputed AUD_UKBB_imputed_chr22
INFO - Processing imputed AUD_UKBB_imputed_chr3
INFO - Processing imputed AUD_UKBB_imputed_chr4
INFO - Processing imputed AUD_UKBB_imputed_chr5
INFO - Processing imputed AUD_UKBB_imputed_chr6
INFO - Processing imputed AUD_UKBB_imputed_chr7
INFO - Processing imputed AUD_UKBB_imputed_chr8
INFO - Processing imputed AUD_UKBB_imputed_chr9
INFO - Processed 663006 imputed variants
INFO - Processing GWAS file /Users/roicick/Desktop/HOT_STUFF/VGLUT_paper/draft_jan21/VGLUT_TWAS/AUD_harmo_final.txt.gz
INFO - Read 2462742 variants
INFO - Kept 2426345 variants as observed
INFO - 3089351 variants
INFO - Filling median
INFO - Sorting by chromosome-position
Traceback (most recent call last):
  File "../summary-gwas-imputation-master/src/gwas_summary_imputation_postprocess.py", line 128, in <module>
    run(args)
  File "../summary-gwas-imputation-master/src/gwas_summary_imputation_postprocess.py", line 100, in run
    process_original_gwas(args, imputed)
  File "../summary-gwas-imputation-master/src/gwas_summary_imputation_postprocess.py", line 60, in process_original_gwas
    g = Genomics.sort(g)
  File "/Users/roicick/Desktop/DNA/summary-gwas-imputation-master/src/genomic_tools_lib/miscellaneous/Genomics.py", line 99, in sort
    chr = [int(x.split("chr")[1]) if chr_re_.search(x) else None for x in d.chromosome]
  File "/Users/roicick/Desktop/DNA/summary-gwas-imputation-master/src/genomic_tools_lib/miscellaneous/Genomics.py", line 99, in <listcomp>
    chr = [int(x.split("chr")[1]) if chr_re_.search(x) else None for x in d.chromosome]
TypeError: expected string or bytes-like object

**Comment by Fnyasimi** [comment]
@romlindien  how does your chromosome column look like  in this `AUD_harmo_final.txt.gz` file?

**Comment by romlindien** [comment]
@Fnyasimi the first lines look like this:

variant_id	panel_variant_id	chromosome	position	effect_allele	non_effect_allele	frequency	pvalue	zscore	effect_size	standard_error	sample_size	n_cases
rs11804171	NA	chr1	788439	A	T	0.057	0.09182	-1.6858743	-0.0256	0.0152	121604	121604
rs2977670	NA	chr1	788511	C	G	0.9428	0.0812	1.7437655	0.0268	0.0154	121604	121604
rs12138618	NA	chr1	814855	A	G	0.0657	0.10800000000000001	-1.607248	-0.0347	0.0216	121604	121604
rs3094315	NA	chr1	817186	A	G	0.7837	0.774	0.2871467	0.0013	0.0046	121604	121604

Thanks!

**Comment by Fnyasimi** [comment]
By any chance is there a row in the chromosome column that is empty? From the error it looks like there is a row somewhere where the software cant find a string in the chromosome column.

**Comment by romlindien** [comment]
Thank you,
I think this was likely to be the issue. I ran all harmo+imputation procedure again and it worked, especially with a better script for the harmo process.

Thanks a lot! I look forward to getting all the results...
Best,
Romain
________________________________________
De : Fnyasimi ***@***.***>
Envoyé : lundi 28 juin 2021 05:54:40
À : hakyimlab/summary-gwas-imputation
Cc : ICICK Romain; Mention
Objet : Re: [hakyimlab/summary-gwas-imputation] post-processing of imputed chromosome files (#14)

By any chance is there a row in the chromosome column that is empty? From the error it looks like there is a row somewhere where the software cant find a string in the chromosome column.
