### ISSUE TITLE
gtex_v8_eur_filtered.txt.gz

### ISSUE THREAD

**Issue by DCousminer** [hakyimlab/summary-gwas-imputation#2]
Thank you for sharing all this super useful code. Would you be willing to also share "gtex_v8_eur_filtered.txt.gz"?

Many thanks!

**Comment by DCousminer** [comment]
And "eur_ld.bed.gz"?

**Comment by hakyim** [comment]
here is the file shared by William

**Comment by hakyim** [comment]
William,

do you also have this file? gtex_v8_eur_filtered.txt.gz

It will be helpful to save it somewhere and link it to the repo's readme or
FAQ?

Thanks
Haky

**Comment by DCousminer** [comment]
> here is the file shared by William

Thanks-- but I'm not seeing the file?

**Comment by DCousminer** [comment]
In general, if you could post any reference files that are publicly available and then have been processed by you guys into a format needed for your scripts, it would be super helpful to share those formatted versions if possible. 
In addition to the ones above, also "gtex_v8_eur_itm.chr1.variants.parquet" and "gtex_v8_eur_itm.variants_metadata.parquet". Thank you!

**Comment by hakyim** [comment]
Alvaro will be sharing all the necessary files shortly with a tutorial

**Comment by Heroico** [comment]
Hi there!

Unfortunately, we can't share the GTEx-specific files for imputation. The individuals' genotypes are protected information that must be accessed through dbGAP.

I'm developing an alternative set of files based on 1000G that can be freely shared, and should be posted in the next few days with a tutorial.

**Comment by DCousminer** [comment]
Thank you!

**Comment by jhchung** [comment]
@Heroico , Thanks for making these tools and resources available.

If we have our own copy of the GTEx dbGaP application, could we generate our own reference to match yours?

**Comment by Heroico** [comment]
Hi all,

We have published detailed documentation on this code, as well as a tutorial based on publicly available 1000G data. The announcement is [here](http://hakyimlab.org/post/2019/gtex-v8-model-release/)

@DCousminer: 
You can find the tutorial [here](https://github.com/hakyimlab/MetaXcan/wiki/Tutorial:-GTEx-v8-MASH-models-integration-with-a-Coronary-Artery-Disease-GWAS); it contains a fully functioning data package, based on 1000 Genome genotypes, aiming to GTEx v8 variants. The first part of the tutorial is concerned with GWAS harmonization+imputation.

@jhchung: Of course you can, the steps I took are described [here](https://github.com/hakyimlab/summary-gwas-imputation/wiki/Reference-Data-Set-Compilation)

Please let me know of any comments or suggestions!
