### ISSUE TITLE
Mismatched order of imputation column and header

### ISSUE THREAD

**Issue by jhchung** [hakyimlab/summary-gwas-imputation#4]
Order of imputation results does not match expected header in [SummaryInputation.py](https://github.com/hakyimlab/summary-gwas-imputation/blob/25b5497d155ed8f1f9546aca60ee8af88e6a86a0/src/genomic_tools_lib/summary_imputation/SummaryInputation.py).

`effect_allele` and `non_effect_allele` order are different in:
 * [`Results` variable](https://github.com/hakyimlab/summary-gwas-imputation/blob/25b5497d155ed8f1f9546aca60ee8af88e6a86a0/src/genomic_tools_lib/summary_imputation/SummaryInputation.py#L33)
* [`_result` function](https://github.com/hakyimlab/summary-gwas-imputation/blob/25b5497d155ed8f1f9546aca60ee8af88e6a86a0/src/genomic_tools_lib/summary_imputation/SummaryInputation.py#L40)

**Comment by Heroico** [comment]
Thanks for reporting this, it is fixed now. The "imputation variant" code was out of sync with the "imputation by variant" code.
For completeness' sake, please note that "imputing by region is preferred" (i.e. specifying a file with approximately independent LD regions with the `-by_region_file` argument)
