### ISSUE TITLE
KeyError: "['n_cases'] not in index"  

### ISSUE THREAD

**Issue by gustavahlberg** [hakyimlab/summary-gwas-imputation#7]

**Comment by Heroico** [comment]
Hi Gustav,

The new code is not constrained to case-control studies, and the summary version (SPrediXcan) makes no difference between quantitative or dichotomous trait.

The column `n_cases` is merely required for format consistency, you can safely fill `n_case` with `NA`. It is only used in other complementary tools like coloc.

Best,

Alvaro
