### ISSUE TITLE
KeyError: "['zscore'] not in index"

### ISSUE THREAD

**Issue by lauraand1705** [hakyimlab/summary-gwas-imputation#8]
Hi,
I am having trouble with gwas_summary_imputation.py after having harmonized my sumstats.
I get the following error:
KeyError: "['zscore'] not in index"

With the script:
python3 gwas_summary_imputation.py \
-by_region_file eur_ld.bed.gz \
-gwas_file meta_harm_200803.tab.gz \
-parquet_genotype chr1.variants.parquet \
-parquet_genotype_metadata variant_metadata.parquet \
-window 100000 \
-parsimony 7 \
-chromosome 1 \
-regularization 0.1 \
-frequency_filter 0.01 \
-sub_batches 5 \
-sub_batch 0 \
--standardise_dosages \
-output meta_harm_imput_200803_chr1_sb0.tab \

Is a zscore necessary for this step?
My input has the following columns:

variant_id	panel_variant_id      chromosome	position	effect_allele	non_effect_allele	frequency	pvalue	effect_size	standard_error	sample_size	n_cases

Thank you for your help.
Best regards,
Laura.

**Comment by Heroico** [comment]
Hi Laura,

I'm assuming you already harmonized the GWAS.

The summary imputation tool indeed needs zscores - it assumes its existence and uses the observed values to impute missing zscores. I suggest re-running harmonization with `zscore` in the generated columns.

Best,

Alvaro
